### ISSUE TITLE
How do I use the browser version

### ISSUE THREAD

**Issue by delebash** [jimp-dev/pngjs3#94]
With pngjs after npm install pngjs  I can import it for the web browser by `import { PNG } from 'pngjs/browser';`
How do I accomplish this with pngjs3?

Thanks!

**Comment by gforge** [comment]
The browser version should be the main version

**Comment by delebash** [comment]
When I use `import {PNG} from "pngjs3";` and try to compile I get Module not found: Can't resolve imported dependency "util"
as well as other errors of the same type.  If I use the original it works fine.    https://github.com/lukeapage/pngjs#browser
`import { PNG } from 'pngjs/browser'`

**Comment by gforge** [comment]
Hmm... Strange, I'll try to look into it but I'm working clinically this week so I wont have any time until next week.

**Comment by delebash** [comment]
Ok thanks whenever you get the time!

**Comment by KTibow** [comment]
@gforge i cant get this to work

**Comment by gforge** [comment]
There seems to have been a package.json bug, it should work in version 6.1.1
