### ISSUE TITLE
Hello from Jimp

### ISSUE THREAD

**Issue by hipstersmoothie** [jimp-dev/pngjs3#96]
Hey! I like that you're maintaining this since pngjs2 seems dead. I'm trying to integrate this project with jimp since it looks like it might fix one of our issues.  I'm finding that you're pre bundling the entire library and not shipping a node version at all. Even when running on node it runs with browserify zlib.

I jump created https://github.com/jimp-dev to house the jimp repo going forward to facilitated collaboration and the long term health of the project. Would you be interested in moving this repo and it's development there? If so I can fix all the builds so all you need worry about is making pings better 😄

**Comment by gforge** [comment]
Exactly how do I transfer the project to Jimp?

**Comment by hipstersmoothie** [comment]
Got to this repo's settings, scroll to the bottom and there should be a transfer option

**Comment by gforge** [comment]
Found it, repo moved :smiley: 

How do we do with the push to npm?

**Comment by hipstersmoothie** [comment]
@gforge Thanks for moving the repo! You could just add me to the package. My username there is `alisowski`.

We also started a discord for developers helping maintain jimp. I think it would be cool for jimp to be an org that manages a bunch of javascript image packages and pull in more packages just like this. Feel free to join us!

https://discord.gg/dF5gfxEb
